version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/app
   overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
   - location: prod-backend/scripts/remove_previous_build
     timeout: 300
     runas: root
  AfterInstall:
   - location: prod-backend/scripts/restart_server
     timeout: 300
     runas: root
