name: Deploy to Backend Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Check if there was changes in stage-backend directory
      - name: Get changed files in the stage-backend folder
        id: changed-files-stage-backend
        uses: tj-actions/changed-files@v37
        with:
          files: stage-backend/** # Alternatively using: `stage-backend` or `stage-backend/*`

      # if there was a change in directory, run deployment
      - name: Run deployment if there was changes in stage-backend directory
        id: stage-backend-deployment
        if: ${{ steps.changed-files-stage-backend.outputs.any_changed == 'true' }}
        run: |
          echo -e "DB_URL=${{ secrets.DEV_DB_URL }}" > ./.env
          echo "${{ secrets.DEV_BACKEND_PRIVATE_KEY }}" > ./private_key.pem
          chmod 600 ./private_key.pem
          scp -o "StrictHostKeyChecking no" -i ./private_key.pem stage-backend/docker-compose.yml ./.env ubuntu@3.129.218.153:/home/ubuntu/app/




